// Generated by CoffeeScript 1.4.0

/*
Background Page Main JavaScript
*/


(function() {

  $(function() {
    var auth_data;
    auth_data = {
      subdomain: localStorage['harvest_subdomain'],
      auth_string: localStorage['harvest_auth_string'],
      username: localStorage['harvest_username']
    };
    if (!(auth_data.subdomain.isBlank() || auth_data.auth_string.isBlank())) {
      window.application = new BackgroundApplication(auth_data.subdomain, auth_data.auth_string);
      setTimeout(window.application.refresh_hours, 500);
      return window.application.start_refresh_interval();
    } else {
      chrome.browserAction.setBadgeText({
        text: '!'
      });
      return console.error('Error initializing Hayfever. Please visit the options page.');
    }
  });

}).call(this);
